return {
    get = function(colors)
        local config = require "one_monokai.config"

        return {
            Constant = { fg = colors.aqua },
            Number = { fg = colors.purple },
            Float = { fg = colors.purple },
            Boolean = { fg = colors.cyan },
            Character = { fg = colors.yellow },
            String = { fg = colors.yellow },
            Type = { fg = colors.aqua },
            Structure = { fg = colors.cyan },
            StorageClass = { fg = colors.cyan },
            Typedef = { fg = colors.aqua },
            Identifier = { fg = colors.green },
            Function = { fg = colors.green },
            Statement = { fg = colors.pink },
            Operator = { fg = colors.pink },
            Label = { fg = colors.pink },
            Keyword = { fg = colors.cyan },
            PreProc = { fg = colors.green },
            Include = { fg = colors.pink },
            Define = { fg = colors.pink },
            Macro = { fg = colors.green },
            PreCondit = { fg = colors.pink },
            Special = { fg = colors.purple },
            SpecialChar = { fg = colors.pink },
            Delimiter = { fg = colors.pink },
            SpecialComment = { fg = colors.cyan },
            Tag = { fg = colors.pink },
            Todo = { fg = colors.orange, bold = true, italic = true },
            Comment = { fg = colors.warm_gray, italic = true },
            Underlined = { fg = colors.green, underline = true },
            Ignore = { fg = colors.yellow },
            Error = { fg = colors.error.fg, bg = colors.error.bg },

            Normal = { fg = colors.fg, bg = config.options.transparent and colors.none or colors.bg },
            FloatTitle = { fg = colors.pink },
            SignColumn = {},
            LineNr = { fg = colors.gray },
            CursorLineNr = { fg = colors.fg },
            ColorColumn = { bg = colors.dark_black },
            Cursor = { fg = colors.bg, bg = colors.fg },
            CursorColumn = { bg = colors.vulcan },
            CursorLine = { bg = colors.vulcan },
            Nontext = { fg = colors.gray },
            StatusLine = { fg = colors.light_gray, bg = colors.darker_black },
            StatusLineNC = { fg = colors.light_gray, bg = colors.dark_black },
            Tabline = { fg = colors.fg, bg = colors.dark_black, reverse = true },
            Visual = { bg = colors.gray },
            Search = { fg = colors.bg, bg = colors.yellow },
            MatchParen = { fg = colors.fg, bold = true, underline = true },
            Question = { fg = colors.yellow },
            ModeMsg = { fg = colors.yellow },
            MoreMsg = { fg = colors.yellow },
            ErrorMsg = { fg = colors.bg, bg = colors.error.fg, standout = true },
            WarningMsg = { fg = colors.yellow },
            VertSplit = { fg = colors.fg },

            SpecialKey = { fg = colors.pink },
            Title = { fg = colors.yellow },
            Directory = { fg = colors.aqua },

            DiffAdd = { fg = colors.git.add },
            DiffDelete = { fg = colors.git.del },
            DiffChange = { fg = colors.git.change },
            DiffText = { fg = colors.bg, bg = colors.cyan },

            Folded = { fg = colors.warm_gray, bg = colors.dark_black },
            FoldColumn = { bg = colors.dark_black },

            Pmenu = { fg = colors.fg },
            PmenuSel = { fg = colors.bg, bg = colors.pink },
            PmenuThumb = { fg = colors.light_black, bg = colors.gray },

            LspReferenceRead = { bg = colors.vulcan, bold = true },
            LspReferenceText = { bg = colors.vulcan, bold = true },
            LspReferenceWrite = { bg = colors.vulcan, bold = true },
        }
    end,
}
