name: check

on:
 push:
   paths:
     - "**.lua"
 pull_request:
   paths:
     - "**.lua"

jobs:
 stylua-check:
   name: "Formatting check with Stylua"
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Lint with stylua
       uses: JohnnyMorganz/stylua-action@1.0.0
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         args: --check lua/ tests/
 selene-check:
     name: "Linter check with Selene"
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - uses: NTBBloodbath/selene-action@v1.0.0
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         args: --display-style=quiet lua/ tests/
