name: check

on:
  pull_request:
    branches:
      - main

jobs:
  stylua-check:
    name: "Formatting check with Stylua"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint with stylua
        uses: JohnnyMorganz/stylua-action@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check lua/ tests/
  selene-check:
    name: "Linter check with Selene"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --display-style=quiet lua/ tests/
