name: commitlint

on: [push, pull_request]

# Cancel any in-progress CI runs for a PR if it is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  commitlint:
    name: Run commitlint on commit ${{ github.ref_name }}/${{ github.sha }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Validate all commits from PR
        run: npx commitlint --from=HEAD~1 --verbose
