name: test

on:
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    name: Run tests on ${{ matrix.os }} with Neovim ${{ matrix.neovim }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            neovim: 0.8.0
            url: https://github.com/neovim/neovim/releases/download/v0.8.0/nvim-linux64.tar.gz
          - os: ubuntu-latest
            neovim: nightly
            url: https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
          - os: macos-latest
            neovim: 0.8.0
            url: https://github.com/neovim/neovim/releases/download/v0.8.0/nvim-macos.tar.gz
          - os: macos-latest
            neovim: nightly
            url: https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: date +%F > todays-date
      - name: Restore cache for today's nightly.
        uses: actions/cache@v2
        with:
          path: _neovim
          key: ${{ runner.os }}-${{ matrix.url }}-${{ hashFiles('todays-date') }}
      - name: Prepare
        run: |
          test -d _neovim || {
            mkdir -p _neovim
            curl -sL ${{ matrix.url }} | tar xzf - --strip-components=1 -C "$PWD/_neovim"
          }
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          ln -s $PWD ~/.local/share/nvim/site/pack/vendor/start
      - name: Run tests
        timeout-minutes: 4
        run: |
          export PATH="$PWD/_neovim/bin:$PATH"
          nvim --version
          make test
